#export CLUSTER_NAME="aj-b2c-backend-eks"
#export AWS_DEFAULT_REGION="ap-south-east"
export KUBECONFIG="${PWD}/kubeconfig_${CLUSTER_NAME}"
export KUBE_CONFIG_PATH="${KUBECONFIG}"
export CLUSTER_ENDPOINT="$(aws eks describe-cluster --name "aj-b2c-backend-eks" --query "cluster.endpoint" --output text)"
